#!/bin/bash
case $# in
#0或1个参数的情况，即c0 -h或c0，直接交给java程序处理
  0)
    java -jar c0Compiler.jar
    ;;
  1)
    java -jar c0Compiler.jar $1
    ;;
  2)
#    两个参数的情况。即c0 -s input或c0 -c input，并且需要重定向输出到文件
#    正则表达式去掉注释
    if [ $1 = "-s" ];then
#      sed -e -zE "//[\s\S]*?\n" $2>temp
#      sed -e -zE "/^[ \t]*\/\*/,/.*\*\//d" temp>temp1
#      python3 removeComments.py $2>temp
      java -jar c0Compiler.jar $1 $2>out
#      rm temp
#      cat ./out
    elif [ $1 = "-c" ]; then
#      sed -e -zE "//[\s\S]*?\n" $2>temp
#      sed -e -zE "/^[ \t]*\/\*/,/.*\*\//d" temp>temp1
#      grep -v "//[\s\S]*?\n" $2>temp
#      grep -v "/^[ \t]*\/\*/,/.*\*\//d" temp>temp1
#      python3 removeComments.py $2>temp
      java -jar c0Compiler.jar $1 $2>out.s
#      rm temp
      ./c0-vm -a out.s out
      rm out.s
    else
        echo "参数错误"
        java -jar c0Compiler.jar
    fi
    ;;
  4)
    if [ $1 = "-s" ];then
      if [ $3 != "-o" ];then
        echo "参数错误"
        java -jar c0Compiler.jar
        exit 0
      fi
#      python3 removeComments.py $2>temp
      java -jar c0Compiler.jar $1 $2>$4
#      rm temp
#      cat $4
    elif [ $1 = "-c" ]; then
      if [ $3 != "-o" ];then
        echo "参数错误"
        java -jar c0Compiler.jar
        exit 0
      fi
#      python3 removeComments.py $2>temp
#      sed -i '/^$/d' temp
#      cat temp
      java -jar c0Compiler.jar $1 $2>out.s
#      rm temp
      ./c0-vm -a out.s $4
      rm out.s
    else
        echo "参数错误"
        java -jar c0Compiler.jar
    fi
    ;;
  *)
    echo "参数错误"
    java -jar c0Compiler.jar
esac